; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:Tytan]
board = Tytan
board_build.arduino.memory_type = qio_opi
board_build.partitions = custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/Tytan>
build_flags =
	${env.build_flags}
	-Iboards/Tytan
	-Os
	-DCORE_DEBUG_LEVEL=1
	-DUSB_as_HID=1
	-DUSE_HSPI_PORT=1
	-DDEVICE_NAME='"Tytan"'

lib_deps =
	${env.lib_deps}
	xreef/PCF8575 library@^2.0.1
